# Generated by Django 4.1.1 on 2022-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lda',
            name='numTopics',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
