# Generated by Django 4.1.1 on 2022-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_lda_numtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lda',
            name='duration',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lda',
            name='endingDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lda',
            name='outputFile',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
