# Generated by Django 4.1.1 on 2022-12-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_lda_duration_alter_lda_endingdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lda",
            name="coherence",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
