# Generated by Django 4.1.1 on 2022-12-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_lda_coherence"),
    ]

    operations = [
        migrations.AddField(
            model_name="lda",
            name="error",
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
