# Generated by Django 4.1.1 on 2022-12-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_lda_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lda",
            name="error",
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
