# Generated by Django 4.1.1 on 2022-12-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_interview_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='interview_id',
            new_name='interview',
        ),
    ]
