# Generated by Django 4.1.1 on 2022-12-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_question_created_at_question_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='question_order',
        ),
    ]
