# Generated by Django 4.1.1 on 2023-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_rename_order_question_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="conclusion",
            field=models.TextField(default=None),
        ),
    ]
