# Generated by Django 4.1.1 on 2023-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0015_question_conclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="lda",
            name="HTMLoutputFile",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
