# Generated by Django 4.1.1 on 2023-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0016_lda_htmloutputfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="bertopic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("startingDate", models.DateTimeField()),
                ("endingDate", models.DateTimeField(null=True)),
                (
                    "duration",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("numTopics", models.DecimalField(decimal_places=3, max_digits=10)),
                ("status", models.CharField(max_length=300)),
                ("corpusFile", models.CharField(max_length=500)),
                ("outputFile", models.CharField(max_length=500, null=True)),
                ("HTMLoutputFile", models.CharField(max_length=500, null=True)),
                ("topic", models.CharField(max_length=50)),
                (
                    "coherence",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                ("error", models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
