# Generated by Django 4.2.4 on 2024-03-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0017_bertopic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reflection", models.TextField()),
                ("conditions", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.interview",
                    ),
                ),
            ],
        ),
    ]
